[package]
name = "kms-encryption-kit"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.5.10"
aws-sdk-kms = "1.50.0"
base64 = "0.22.1"
ed25519-dalek = "2.1.1"
serde_json = "1.0.133"
solana-sdk = "2.1.2"
tempfile = "3.14.0"
tokio = { version = "1.41.1", features = ["full"] }
